### PR TITLE
Single feature menu force

### PR DESCRIPTION
**Pull request by Miindaugas**
So we have this function in Tracks when we click on a cluster of features it lists all features.

Screenshot from 2021-06-17 16-22-27

Looking into code it looks like some tracks try to display single feature menu right away.
```
  click: function (e) {
    var buffer = 3;
    var x = e.pageX - this.container.parent().offset().left + this.browser.scaledStart - buffer;
    var y = e.pageY - $(e.target).offset().top - buffer;
    var f = this[e.target.className === 'labels' ? 'labelPositions' : 'featurePositions'].search({ x: x, y: y, w: 2*buffer, h: 2*buffer }).sort(function (a, b) { return a.sort - b.sort; })[0];

    if (f) {
      this.browser.makeMenu(f, e, this.track);
    }
  }
```
 
I'm thinking maybe bring in "forceMenu" would be better and just use forceMenu:true to display first feature from clicked cluster.
Instead of having this click function.

Screenshot from 2021-06-17 16-36-10

### CODE REVIEW

**Review by MindaugasDukauskas — APPROVED** [review]
Looks good

**Comment by tomratcliffe** [comment]
So is this forcibly opening two menus when clicking on a feature? The grouped menu, and the first of those features?
Or does it stop from opening the grouped feature menu, so you would have to be precise when clicking?

**Comment by Miindaugas** [comment]
> So is this forcibly opening two menus when clicking on a feature? The grouped menu, and the first of those features?
> Or does it stop from opening the grouped feature menu, so you would have to be precise when clicking?

It will open Feature menu right away. Single menu. It does stop from opening grouped feature menu.

**Comment by Miindaugas** [comment]
@tomratcliffe Do you think having gouped feature menu is worth having? i assume that code exists to avoid this.

**Review by tomratcliffe — APPROVED** [review]
Thanks - I think it makes sense to have it as a config option like you have done :+1: Even if we tend to often have it turned on!

**Pull request merged**
